import type { Metadata } from "next";
import { Geist, Geist_Mono , Lato , Roboto_Mono } from "next/font/google";
import "./globals.css";

const robotoMono  =Roboto_Mono({
  variable:'--font-Roboto-Mono',
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.className}   antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
